name: master
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Run a one-line script
       run: echo Hello, world from master!
     - uses: actions/checkout@master  
#     - name: Microsoft Teams Deploy Card
#       uses: toko-bifrost/ms-teams-deploy-card@3.1.2
#       with:
#         webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}     
#         github-token: ${{ github.token }}
#         environment: None
#         timezone: "Asia/Kolkata"
#         card-layout-start: compact 
#         card-layout-exit: compact 
#         show-on-start: true 
#         show-on-exit: true 
#         show-on-failure: true         
#         custom-facts: |
#           - name: ImageTag
#             value: Imagetag text
#         enable-view-status-action: true 
#         enable-review-diffs-action: true 
#         view-status-action-text: "View Status"
    
    
